### ISSUE TITLE
Por que não usar github pages ?

### ISSUE THREAD

**Issue by claytonaalves** [zaioll/blog#1]
O github pages te possibilita hospedar sites estáticos de forma gratuita.

Veja um exemplo: http://claytonaalves.github.io/

**Comment by zaioll** [comment]
Antes mesmo de analisar e responder, já posso apontar um bom motivo (pra mim) pelo qual não é uma opção: o domínio. Isso vai contra a minha proposta. Liberdade ao invés de comodidade.
Contudo, vou dar uma olhada pra pelo menos conhecer mais sobre.

**Comment by claytonaalves** [comment]
Vc pode apontar qualquer domínio. Eu que não quis criar um.
